baseurl = "https://download60.github.io"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode = "en"
resourceDir = "../resources"
DefaultContentLanguage = "en"
Paginate     = false

PygmentsCodeFences = true
PygmentsStyle      = "monokai"


buildFuture = true

[author]
     name = "wahyu6070"
     
[sitemap]
  changefreq = "always"
  priority = 0.8
  filename = "sitemap.xml"
[permalinks]
  download     = "/:year:month/:slug"
  
